services:
    db:
        image: mariadb:11
        environment:
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-db}
            MYSQL_USER: ${WORDPRESS_DB_USER:-db}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            woo-ai-demo-network:

    adminer:
        image: adminer
        ports:
            - "${ADMINER_HOST_PORT:-8081}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            woo-ai-demo-network:

    wordpress:
        build: ./
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-http://localhost:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-http://localhost:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','http://localhost:${WORDPRESS_HOST_PORT:-8080}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','http://localhost:${WORDPRESS_HOST_PORT:-8080}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
        volumes:
            - ./:/var/www/
        ports:
            - "${WORDPRESS_HOST_PORT:-8080}:80"
        depends_on:
            - db
        networks:
            woo-ai-demo-network:

    wpcron:
        image: wordpress:cli
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-http://localhost:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-http://localhost:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','http://localhost:${WORDPRESS_HOST_PORT:-8080}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','http://localhost:${WORDPRESS_HOST_PORT:-8080}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
        volumes:
            - ./html:/var/www/html
        networks:
            woo-ai-demo-network:
        depends_on:
            - wordpress
        command: >
            /bin/bash -c " \
            set -x; \
            until wp db check --skip-ssl --path=/var/www/html; do \
            echo 'Waiting for database connection...' && sleep 5; \
            done; \
            while true; do \
            wp cron event run --due-now --path=/var/www/html 1>/dev/stdout 2>&1 || true; \
            sleep 900; \
            done;"

    weaviate:
        command:
            - --host
            - 0.0.0.0
            - --port
            - "8080"
            - --scheme
            - http
        image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
        ports:
            - 8082:8080
            - 50051:50051
        volumes:
            - weaviate_data:/var/lib/weaviate
        restart: on-failure:0
        environment:
            CONTEXTIONARY_URL: contextionary:9999
            SPELLCHECK_INFERENCE_API: "http://text-spellcheck:8080"
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
            PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
            DEFAULT_VECTORIZER_MODULE: "text2vec-contextionary"
            ENABLE_MODULES: "text2vec-contextionary,text-spellcheck"
            CLUSTER_HOSTNAME: "node1"
        networks:
            woo-ai-demo-network:
    contextionary:
        environment:
            OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
            EXTENSIONS_STORAGE_MODE: weaviate
            EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
            NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
            ENABLE_COMPOUND_SPLITTING: "false"
        image: cr.weaviate.io/semitechnologies/contextionary:en0.16.0-v1.2.1
        ports:
            - 9999:9999
        networks:
            woo-ai-demo-network:
    text-spellcheck:
        image: cr.weaviate.io/semitechnologies/text-spellcheck-model:pyspellchecker-en
        networks:
            woo-ai-demo-network:
    weaviate-ui:
        image: naaive/weaviate-ui:latest
        ports:
            - 8083:7777
        restart: unless-stopped
        depends_on:
            - weaviate
        environment:
            WEAVIATE_URL: "http://weaviate:8080"
        networks:
            woo-ai-demo-network:

    wpcli:
        image: wordpress:cli
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-http://localhost:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-http://localhost:${WORDPRESS_HOST_PORT:-8080}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','http://localhost:${WORDPRESS_HOST_PORT:-8080}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','http://localhost:${WORDPRESS_HOST_PORT:-8080}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
        volumes:
            - ./html:/var/www/html
        depends_on:
            - wordpress
        command: >
            sh -c " \
            set -x; \
            until wp db check --skip-ssl --path=/var/www/html; do \
            echo 'Waiting for database connection...' && sleep 5; \
            done; \
            if ! wp core is-installed --path=/var/www/html; then \
            wp core install --url=${WORDPRESS_CONFIG_WP_HOME:-http://localhost:${WORDPRESS_HOST_PORT:-80}} \
            --title=\"${WORDPRESS_SITE_TITLE:-WordPress Site}\" \
            --admin_user=\"${WORDPRESS_ADMIN_USER:-admin}\" \
            --admin_password=\"${WORDPRESS_ADMIN_PASSWORD:-admin}\" \
            --admin_email=\"${WORDPRESS_ADMIN_EMAIL:-admin@example.com}\" \
            --path=/var/www/html \
            --skip-plugins \
            --skip-themes; \
            fi; \
            if [ -n \"${WORDPRESS_PLUGINS_TO_ACTIVATE:-woocommerce wpsolr-free}\" ]; then wp plugin activate ${WORDPRESS_PLUGINS_TO_ACTIVATE:-woocommerce wpsolr-free} --path=/var/www/html; fi; \
            wp wpsolr import-settings-json dev/wpsolr-free/settings.json --path=/var/www/html ; \
            wp wpsolr index-reindex 0EE76D5EDD73E0E0F72D9E353901FB18 --post-types=category,product,product_cat,product_tag; \
            curl https://raw.githubusercontent.com/AndrewJDawes/woo-sample-data-set/refs/heads/main/products.csv -o /var/www/html/wp-content/uploads/products.csv && \
            curl https://raw.githubusercontent.com/AndrewJDawes/woo-sample-data-set/refs/heads/main/mappings.csv -o /var/www/html/wp-content/uploads/mappings.csv && \
            wp wc import-csv /var/www/html/wp-content/uploads/products.csv --mappings=/var/www/html/wp-content/uploads/mappings.csv --path=/var/www/html --user=\"${WORDPRESS_ADMIN_USER:-admin}\"; \
            sleep infinity;"
        networks:
            woo-ai-demo-network:

networks:
    woo-ai-demo-network:
        external: true

volumes:
    db_data:
    weaviate_data:
