services:
    wordpress:
        build: ./
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-db}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db:3306}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-sdg_}
            WORDPRESS_CONFIG_WP_HOME: ${WORDPRESS_CONFIG_WP_HOME:-http://localhost:${WORDPRESS_HOST_PORT:-80}}
            WORDPRESS_CONFIG_WP_SITEURL: ${WORDPRESS_CONFIG_WP_SITEURL:-http://localhost:${WORDPRESS_HOST_PORT:-80}}
            WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA:-define('WP_HOME',getenv_docker('WORDPRESS_CONFIG_WP_HOME','http://localhost:${WORDPRESS_HOST_PORT:-80}')); define('WP_SITEURL',getenv_docker('WORDPRESS_CONFIG_WP_SITEURL','http://localhost:${WORDPRESS_HOST_PORT:-80}')); define( 'FS_METHOD', 'direct'); define( 'DISABLE_WP_CRON', true ); define( 'WP_DEBUG_LOG', true); define( 'WP_DEBUG_DISPLAY', false);}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
        volumes:
            - ./:/var/www/
        ports:
            - "${WORDPRESS_HOST_PORT:-80}:80"
        depends_on:
            - db
        networks:
            woo-ai-demo-network:

    db:
        image: mysql/mysql-server:8.0 # ARM-compatible version
        environment:
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-db}
            MYSQL_USER: ${WORDPRESS_DB_USER:-db}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            woo-ai-demo-network:

    adminer:
        image: adminer
        ports:
            - "${ADMINER_HOST_PORT:-8080}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            woo-ai-demo-network:

networks:
    woo-ai-demo-network:

volumes:
    db_data:
